# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: heltayb <heltayb@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/21 19:02:56 by heltayb           #+#    #+#              #
#    Updated: 2024/07/26 19:14:06 by heltayb          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	cc -I mlx   main.c mlx/libmlx.a -framework OpenGL -framework AppKit -o raycast && ./raycast
3d:
	cc -I mlx   main3d.c mlx/libmlx.a -framework OpenGL -framework AppKit -o raycast3d && ./raycast3d